### ISSUE TITLE
Recompile in 2023 as Google translate/machine learning is better now?

### ISSUE THREAD

**Issue by mondve23** [GarnetSunset/Ishin-Machine-Translation#19]
Should be worth trying, as machine learning language models are much better than 2 years ago. I can't recompile this myself as explained in the thread below - the requirements are not clear, missing packages.

**Comment by aye228heaven** [comment]
Yes.  You can also try using another machine translator – DeepL. It seemed to me that he had a more accurate translation than Google

**Comment by aye228heaven** [comment]
Or if you recompile this translation, then here is a link to the pkg file: https://archive.org/details/PS3-Ishin-GT

**Comment by GarnetSunset** [comment]
Oh hey there, yeah, definitely not remaking it unfortunately, as it costs money to do. That's the issue on a surface level. Not looking to pay how ever much it is, but also this isn't a "real" way to play this game, this mod should be considered a joke and an oddity.
